# TCL File Generated by Component Editor 15.0
# Sun Jun 14 21:49:49 PDT 2015
# DO NOT MODIFY


# 
# clk_divide_8k "clk_divide_8k" v1.0
#  2015.06.14.21:49:49
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module clk_divide_8k
# 
set_module_property DESCRIPTION ""
set_module_property NAME clk_divide_8k
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME clk_divide_8k
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL clk_divide
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file clk_divide.v VERILOG PATH verilog/avalon_mm_master/clk_divide.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point clock_out
# 
add_interface clock_out clock start
set_interface_property clock_out associatedDirectClock ""
set_interface_property clock_out clockRate 0
set_interface_property clock_out clockRateKnown false
set_interface_property clock_out ENABLED true
set_interface_property clock_out EXPORT_OF ""
set_interface_property clock_out PORT_NAME_MAP ""
set_interface_property clock_out CMSIS_SVD_VARIABLES ""
set_interface_property clock_out SVD_ADDRESS_GROUP ""

add_interface_port clock_out clk_out clk Output 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clk_rst reset Input 1


# 
# connection point clock_reset_out
# 
add_interface clock_reset_out reset start
set_interface_property clock_reset_out associatedClock clock
set_interface_property clock_reset_out associatedDirectReset ""
set_interface_property clock_reset_out associatedResetSinks ""
set_interface_property clock_reset_out synchronousEdges DEASSERT
set_interface_property clock_reset_out ENABLED true
set_interface_property clock_reset_out EXPORT_OF ""
set_interface_property clock_reset_out PORT_NAME_MAP ""
set_interface_property clock_reset_out CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset_out SVD_ADDRESS_GROUP ""

add_interface_port clock_reset_out clk_rst_out reset Output 1

