// top_LPC_FPGA_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module top_LPC_FPGA_mm_interconnect_0 (
		input  wire        clk_50M_clk_clk,                                             //                                           clk_50M_clk.clk
		input  wire        DDR3_interface_mp_cmd_reset_n_1_reset_bridge_in_reset_reset, // DDR3_interface_mp_cmd_reset_n_1_reset_bridge_in_reset.reset
		input  wire        read_master_clock_reset_reset_reset_bridge_in_reset_reset,   //   read_master_clock_reset_reset_reset_bridge_in_reset.reset
		input  wire [31:0] read_master_avalon_master_address,                           //                             read_master_avalon_master.address
		output wire        read_master_avalon_master_waitrequest,                       //                                                      .waitrequest
		input  wire [2:0]  read_master_avalon_master_burstcount,                        //                                                      .burstcount
		input  wire [1:0]  read_master_avalon_master_byteenable,                        //                                                      .byteenable
		input  wire        read_master_avalon_master_read,                              //                                                      .read
		output wire [15:0] read_master_avalon_master_readdata,                          //                                                      .readdata
		output wire        read_master_avalon_master_readdatavalid,                     //                                                      .readdatavalid
		output wire [24:0] DDR3_interface_avl_1_address,                                //                                  DDR3_interface_avl_1.address
		output wire        DDR3_interface_avl_1_write,                                  //                                                      .write
		output wire        DDR3_interface_avl_1_read,                                   //                                                      .read
		input  wire [31:0] DDR3_interface_avl_1_readdata,                               //                                                      .readdata
		output wire [31:0] DDR3_interface_avl_1_writedata,                              //                                                      .writedata
		output wire        DDR3_interface_avl_1_beginbursttransfer,                     //                                                      .beginbursttransfer
		output wire [2:0]  DDR3_interface_avl_1_burstcount,                             //                                                      .burstcount
		output wire [3:0]  DDR3_interface_avl_1_byteenable,                             //                                                      .byteenable
		input  wire        DDR3_interface_avl_1_readdatavalid,                          //                                                      .readdatavalid
		input  wire        DDR3_interface_avl_1_waitrequest                             //                                                      .waitrequest
	);

	wire          read_master_avalon_master_translator_avalon_universal_master_0_waitrequest;   // read_master_avalon_master_agent:av_waitrequest -> read_master_avalon_master_translator:uav_waitrequest
	wire   [15:0] read_master_avalon_master_translator_avalon_universal_master_0_readdata;      // read_master_avalon_master_agent:av_readdata -> read_master_avalon_master_translator:uav_readdata
	wire          read_master_avalon_master_translator_avalon_universal_master_0_debugaccess;   // read_master_avalon_master_translator:uav_debugaccess -> read_master_avalon_master_agent:av_debugaccess
	wire   [31:0] read_master_avalon_master_translator_avalon_universal_master_0_address;       // read_master_avalon_master_translator:uav_address -> read_master_avalon_master_agent:av_address
	wire          read_master_avalon_master_translator_avalon_universal_master_0_read;          // read_master_avalon_master_translator:uav_read -> read_master_avalon_master_agent:av_read
	wire    [1:0] read_master_avalon_master_translator_avalon_universal_master_0_byteenable;    // read_master_avalon_master_translator:uav_byteenable -> read_master_avalon_master_agent:av_byteenable
	wire          read_master_avalon_master_translator_avalon_universal_master_0_readdatavalid; // read_master_avalon_master_agent:av_readdatavalid -> read_master_avalon_master_translator:uav_readdatavalid
	wire          read_master_avalon_master_translator_avalon_universal_master_0_lock;          // read_master_avalon_master_translator:uav_lock -> read_master_avalon_master_agent:av_lock
	wire          read_master_avalon_master_translator_avalon_universal_master_0_write;         // read_master_avalon_master_translator:uav_write -> read_master_avalon_master_agent:av_write
	wire   [15:0] read_master_avalon_master_translator_avalon_universal_master_0_writedata;     // read_master_avalon_master_translator:uav_writedata -> read_master_avalon_master_agent:av_writedata
	wire    [3:0] read_master_avalon_master_translator_avalon_universal_master_0_burstcount;    // read_master_avalon_master_translator:uav_burstcount -> read_master_avalon_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                            // rsp_mux:src_valid -> read_master_avalon_master_agent:rp_valid
	wire   [85:0] rsp_mux_src_data;                                                             // rsp_mux:src_data -> read_master_avalon_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                            // read_master_avalon_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                          // rsp_mux:src_channel -> read_master_avalon_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                    // rsp_mux:src_startofpacket -> read_master_avalon_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                      // rsp_mux:src_endofpacket -> read_master_avalon_master_agent:rp_endofpacket
	wire   [31:0] ddr3_interface_avl_1_agent_m0_readdata;                                       // DDR3_interface_avl_1_translator:uav_readdata -> DDR3_interface_avl_1_agent:m0_readdata
	wire          ddr3_interface_avl_1_agent_m0_waitrequest;                                    // DDR3_interface_avl_1_translator:uav_waitrequest -> DDR3_interface_avl_1_agent:m0_waitrequest
	wire          ddr3_interface_avl_1_agent_m0_debugaccess;                                    // DDR3_interface_avl_1_agent:m0_debugaccess -> DDR3_interface_avl_1_translator:uav_debugaccess
	wire   [31:0] ddr3_interface_avl_1_agent_m0_address;                                        // DDR3_interface_avl_1_agent:m0_address -> DDR3_interface_avl_1_translator:uav_address
	wire    [3:0] ddr3_interface_avl_1_agent_m0_byteenable;                                     // DDR3_interface_avl_1_agent:m0_byteenable -> DDR3_interface_avl_1_translator:uav_byteenable
	wire          ddr3_interface_avl_1_agent_m0_read;                                           // DDR3_interface_avl_1_agent:m0_read -> DDR3_interface_avl_1_translator:uav_read
	wire          ddr3_interface_avl_1_agent_m0_readdatavalid;                                  // DDR3_interface_avl_1_translator:uav_readdatavalid -> DDR3_interface_avl_1_agent:m0_readdatavalid
	wire          ddr3_interface_avl_1_agent_m0_lock;                                           // DDR3_interface_avl_1_agent:m0_lock -> DDR3_interface_avl_1_translator:uav_lock
	wire   [31:0] ddr3_interface_avl_1_agent_m0_writedata;                                      // DDR3_interface_avl_1_agent:m0_writedata -> DDR3_interface_avl_1_translator:uav_writedata
	wire          ddr3_interface_avl_1_agent_m0_write;                                          // DDR3_interface_avl_1_agent:m0_write -> DDR3_interface_avl_1_translator:uav_write
	wire    [4:0] ddr3_interface_avl_1_agent_m0_burstcount;                                     // DDR3_interface_avl_1_agent:m0_burstcount -> DDR3_interface_avl_1_translator:uav_burstcount
	wire          ddr3_interface_avl_1_agent_rf_source_valid;                                   // DDR3_interface_avl_1_agent:rf_source_valid -> DDR3_interface_avl_1_agent_rsp_fifo:in_valid
	wire  [104:0] ddr3_interface_avl_1_agent_rf_source_data;                                    // DDR3_interface_avl_1_agent:rf_source_data -> DDR3_interface_avl_1_agent_rsp_fifo:in_data
	wire          ddr3_interface_avl_1_agent_rf_source_ready;                                   // DDR3_interface_avl_1_agent_rsp_fifo:in_ready -> DDR3_interface_avl_1_agent:rf_source_ready
	wire          ddr3_interface_avl_1_agent_rf_source_startofpacket;                           // DDR3_interface_avl_1_agent:rf_source_startofpacket -> DDR3_interface_avl_1_agent_rsp_fifo:in_startofpacket
	wire          ddr3_interface_avl_1_agent_rf_source_endofpacket;                             // DDR3_interface_avl_1_agent:rf_source_endofpacket -> DDR3_interface_avl_1_agent_rsp_fifo:in_endofpacket
	wire          ddr3_interface_avl_1_agent_rsp_fifo_out_valid;                                // DDR3_interface_avl_1_agent_rsp_fifo:out_valid -> DDR3_interface_avl_1_agent:rf_sink_valid
	wire  [104:0] ddr3_interface_avl_1_agent_rsp_fifo_out_data;                                 // DDR3_interface_avl_1_agent_rsp_fifo:out_data -> DDR3_interface_avl_1_agent:rf_sink_data
	wire          ddr3_interface_avl_1_agent_rsp_fifo_out_ready;                                // DDR3_interface_avl_1_agent:rf_sink_ready -> DDR3_interface_avl_1_agent_rsp_fifo:out_ready
	wire          ddr3_interface_avl_1_agent_rsp_fifo_out_startofpacket;                        // DDR3_interface_avl_1_agent_rsp_fifo:out_startofpacket -> DDR3_interface_avl_1_agent:rf_sink_startofpacket
	wire          ddr3_interface_avl_1_agent_rsp_fifo_out_endofpacket;                          // DDR3_interface_avl_1_agent_rsp_fifo:out_endofpacket -> DDR3_interface_avl_1_agent:rf_sink_endofpacket
	wire          ddr3_interface_avl_1_agent_rdata_fifo_src_valid;                              // DDR3_interface_avl_1_agent:rdata_fifo_src_valid -> DDR3_interface_avl_1_agent_rdata_fifo:in_valid
	wire   [33:0] ddr3_interface_avl_1_agent_rdata_fifo_src_data;                               // DDR3_interface_avl_1_agent:rdata_fifo_src_data -> DDR3_interface_avl_1_agent_rdata_fifo:in_data
	wire          ddr3_interface_avl_1_agent_rdata_fifo_src_ready;                              // DDR3_interface_avl_1_agent_rdata_fifo:in_ready -> DDR3_interface_avl_1_agent:rdata_fifo_src_ready
	wire          read_master_avalon_master_agent_cp_valid;                                     // read_master_avalon_master_agent:cp_valid -> router:sink_valid
	wire   [85:0] read_master_avalon_master_agent_cp_data;                                      // read_master_avalon_master_agent:cp_data -> router:sink_data
	wire          read_master_avalon_master_agent_cp_ready;                                     // router:sink_ready -> read_master_avalon_master_agent:cp_ready
	wire          read_master_avalon_master_agent_cp_startofpacket;                             // read_master_avalon_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          read_master_avalon_master_agent_cp_endofpacket;                               // read_master_avalon_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                             // router:src_valid -> cmd_demux:sink_valid
	wire   [85:0] router_src_data;                                                              // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                             // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                           // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                     // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                       // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          ddr3_interface_avl_1_agent_rp_valid;                                          // DDR3_interface_avl_1_agent:rp_valid -> router_001:sink_valid
	wire  [103:0] ddr3_interface_avl_1_agent_rp_data;                                           // DDR3_interface_avl_1_agent:rp_data -> router_001:sink_data
	wire          ddr3_interface_avl_1_agent_rp_ready;                                          // router_001:sink_ready -> DDR3_interface_avl_1_agent:rp_ready
	wire          ddr3_interface_avl_1_agent_rp_startofpacket;                                  // DDR3_interface_avl_1_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          ddr3_interface_avl_1_agent_rp_endofpacket;                                    // DDR3_interface_avl_1_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                         // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire   [85:0] cmd_demux_src0_data;                                                          // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                         // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                       // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                 // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                   // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                         // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire   [85:0] rsp_demux_src0_data;                                                          // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                         // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                       // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                 // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                   // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          cmd_mux_src_valid;                                                            // cmd_mux:src_valid -> DDR3_interface_avl_1_cmd_width_adapter:in_valid
	wire   [85:0] cmd_mux_src_data;                                                             // cmd_mux:src_data -> DDR3_interface_avl_1_cmd_width_adapter:in_data
	wire          cmd_mux_src_ready;                                                            // DDR3_interface_avl_1_cmd_width_adapter:in_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                          // cmd_mux:src_channel -> DDR3_interface_avl_1_cmd_width_adapter:in_channel
	wire          cmd_mux_src_startofpacket;                                                    // cmd_mux:src_startofpacket -> DDR3_interface_avl_1_cmd_width_adapter:in_startofpacket
	wire          cmd_mux_src_endofpacket;                                                      // cmd_mux:src_endofpacket -> DDR3_interface_avl_1_cmd_width_adapter:in_endofpacket
	wire          ddr3_interface_avl_1_cmd_width_adapter_src_valid;                             // DDR3_interface_avl_1_cmd_width_adapter:out_valid -> DDR3_interface_avl_1_agent:cp_valid
	wire  [103:0] ddr3_interface_avl_1_cmd_width_adapter_src_data;                              // DDR3_interface_avl_1_cmd_width_adapter:out_data -> DDR3_interface_avl_1_agent:cp_data
	wire          ddr3_interface_avl_1_cmd_width_adapter_src_ready;                             // DDR3_interface_avl_1_agent:cp_ready -> DDR3_interface_avl_1_cmd_width_adapter:out_ready
	wire    [0:0] ddr3_interface_avl_1_cmd_width_adapter_src_channel;                           // DDR3_interface_avl_1_cmd_width_adapter:out_channel -> DDR3_interface_avl_1_agent:cp_channel
	wire          ddr3_interface_avl_1_cmd_width_adapter_src_startofpacket;                     // DDR3_interface_avl_1_cmd_width_adapter:out_startofpacket -> DDR3_interface_avl_1_agent:cp_startofpacket
	wire          ddr3_interface_avl_1_cmd_width_adapter_src_endofpacket;                       // DDR3_interface_avl_1_cmd_width_adapter:out_endofpacket -> DDR3_interface_avl_1_agent:cp_endofpacket
	wire          router_001_src_valid;                                                         // router_001:src_valid -> DDR3_interface_avl_1_rsp_width_adapter:in_valid
	wire  [103:0] router_001_src_data;                                                          // router_001:src_data -> DDR3_interface_avl_1_rsp_width_adapter:in_data
	wire          router_001_src_ready;                                                         // DDR3_interface_avl_1_rsp_width_adapter:in_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                       // router_001:src_channel -> DDR3_interface_avl_1_rsp_width_adapter:in_channel
	wire          router_001_src_startofpacket;                                                 // router_001:src_startofpacket -> DDR3_interface_avl_1_rsp_width_adapter:in_startofpacket
	wire          router_001_src_endofpacket;                                                   // router_001:src_endofpacket -> DDR3_interface_avl_1_rsp_width_adapter:in_endofpacket
	wire          ddr3_interface_avl_1_rsp_width_adapter_src_valid;                             // DDR3_interface_avl_1_rsp_width_adapter:out_valid -> rsp_demux:sink_valid
	wire   [85:0] ddr3_interface_avl_1_rsp_width_adapter_src_data;                              // DDR3_interface_avl_1_rsp_width_adapter:out_data -> rsp_demux:sink_data
	wire          ddr3_interface_avl_1_rsp_width_adapter_src_ready;                             // rsp_demux:sink_ready -> DDR3_interface_avl_1_rsp_width_adapter:out_ready
	wire    [0:0] ddr3_interface_avl_1_rsp_width_adapter_src_channel;                           // DDR3_interface_avl_1_rsp_width_adapter:out_channel -> rsp_demux:sink_channel
	wire          ddr3_interface_avl_1_rsp_width_adapter_src_startofpacket;                     // DDR3_interface_avl_1_rsp_width_adapter:out_startofpacket -> rsp_demux:sink_startofpacket
	wire          ddr3_interface_avl_1_rsp_width_adapter_src_endofpacket;                       // DDR3_interface_avl_1_rsp_width_adapter:out_endofpacket -> rsp_demux:sink_endofpacket
	wire          ddr3_interface_avl_1_agent_rdata_fifo_out_valid;                              // DDR3_interface_avl_1_agent_rdata_fifo:out_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] ddr3_interface_avl_1_agent_rdata_fifo_out_data;                               // DDR3_interface_avl_1_agent_rdata_fifo:out_data -> avalon_st_adapter:in_0_data
	wire          ddr3_interface_avl_1_agent_rdata_fifo_out_ready;                              // avalon_st_adapter:in_0_ready -> DDR3_interface_avl_1_agent_rdata_fifo:out_ready
	wire          avalon_st_adapter_out_0_valid;                                                // avalon_st_adapter:out_0_valid -> DDR3_interface_avl_1_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                                 // avalon_st_adapter:out_0_data -> DDR3_interface_avl_1_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                                // DDR3_interface_avl_1_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                                // avalon_st_adapter:out_0_error -> DDR3_interface_avl_1_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (3),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (4),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) read_master_avalon_master_translator (
		.clk                    (clk_50M_clk_clk),                                                              //                       clk.clk
		.reset                  (read_master_clock_reset_reset_reset_bridge_in_reset_reset),                    //                     reset.reset
		.uav_address            (read_master_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (read_master_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (read_master_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (read_master_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (read_master_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (read_master_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (read_master_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (read_master_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (read_master_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (read_master_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (read_master_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (read_master_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (read_master_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (read_master_avalon_master_burstcount),                                         //                          .burstcount
		.av_byteenable          (read_master_avalon_master_byteenable),                                         //                          .byteenable
		.av_read                (read_master_avalon_master_read),                                               //                          .read
		.av_readdata            (read_master_avalon_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (read_master_avalon_master_readdatavalid),                                      //                          .readdatavalid
		.av_beginbursttransfer  (1'b0),                                                                         //               (terminated)
		.av_begintransfer       (1'b0),                                                                         //               (terminated)
		.av_chipselect          (1'b0),                                                                         //               (terminated)
		.av_write               (1'b0),                                                                         //               (terminated)
		.av_writedata           (16'b0000000000000000),                                                         //               (terminated)
		.av_lock                (1'b0),                                                                         //               (terminated)
		.av_debugaccess         (1'b0),                                                                         //               (terminated)
		.uav_clken              (),                                                                             //               (terminated)
		.av_clken               (1'b1),                                                                         //               (terminated)
		.uav_response           (2'b00),                                                                        //               (terminated)
		.av_response            (),                                                                             //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                         //               (terminated)
		.av_writeresponsevalid  ()                                                                              //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (25),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (3),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (5),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) ddr3_interface_avl_1_translator (
		.clk                    (clk_50M_clk_clk),                                           //                      clk.clk
		.reset                  (read_master_clock_reset_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (ddr3_interface_avl_1_agent_m0_address),                     // avalon_universal_slave_0.address
		.uav_burstcount         (ddr3_interface_avl_1_agent_m0_burstcount),                  //                         .burstcount
		.uav_read               (ddr3_interface_avl_1_agent_m0_read),                        //                         .read
		.uav_write              (ddr3_interface_avl_1_agent_m0_write),                       //                         .write
		.uav_waitrequest        (ddr3_interface_avl_1_agent_m0_waitrequest),                 //                         .waitrequest
		.uav_readdatavalid      (ddr3_interface_avl_1_agent_m0_readdatavalid),               //                         .readdatavalid
		.uav_byteenable         (ddr3_interface_avl_1_agent_m0_byteenable),                  //                         .byteenable
		.uav_readdata           (ddr3_interface_avl_1_agent_m0_readdata),                    //                         .readdata
		.uav_writedata          (ddr3_interface_avl_1_agent_m0_writedata),                   //                         .writedata
		.uav_lock               (ddr3_interface_avl_1_agent_m0_lock),                        //                         .lock
		.uav_debugaccess        (ddr3_interface_avl_1_agent_m0_debugaccess),                 //                         .debugaccess
		.av_address             (DDR3_interface_avl_1_address),                              //      avalon_anti_slave_0.address
		.av_write               (DDR3_interface_avl_1_write),                                //                         .write
		.av_read                (DDR3_interface_avl_1_read),                                 //                         .read
		.av_readdata            (DDR3_interface_avl_1_readdata),                             //                         .readdata
		.av_writedata           (DDR3_interface_avl_1_writedata),                            //                         .writedata
		.av_beginbursttransfer  (DDR3_interface_avl_1_beginbursttransfer),                   //                         .beginbursttransfer
		.av_burstcount          (DDR3_interface_avl_1_burstcount),                           //                         .burstcount
		.av_byteenable          (DDR3_interface_avl_1_byteenable),                           //                         .byteenable
		.av_readdatavalid       (DDR3_interface_avl_1_readdatavalid),                        //                         .readdatavalid
		.av_waitrequest         (DDR3_interface_avl_1_waitrequest),                          //                         .waitrequest
		.av_begintransfer       (),                                                          //              (terminated)
		.av_writebyteenable     (),                                                          //              (terminated)
		.av_lock                (),                                                          //              (terminated)
		.av_chipselect          (),                                                          //              (terminated)
		.av_clken               (),                                                          //              (terminated)
		.uav_clken              (1'b0),                                                      //              (terminated)
		.av_debugaccess         (),                                                          //              (terminated)
		.av_outputenable        (),                                                          //              (terminated)
		.uav_response           (),                                                          //              (terminated)
		.av_response            (2'b00),                                                     //              (terminated)
		.uav_writeresponsevalid (),                                                          //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                       //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (85),
		.PKT_ORI_BURST_SIZE_L      (83),
		.PKT_RESPONSE_STATUS_H     (82),
		.PKT_RESPONSE_STATUS_L     (81),
		.PKT_QOS_H                 (70),
		.PKT_QOS_L                 (70),
		.PKT_DATA_SIDEBAND_H       (68),
		.PKT_DATA_SIDEBAND_L       (68),
		.PKT_ADDR_SIDEBAND_H       (67),
		.PKT_ADDR_SIDEBAND_L       (67),
		.PKT_BURST_TYPE_H          (66),
		.PKT_BURST_TYPE_L          (65),
		.PKT_CACHE_H               (80),
		.PKT_CACHE_L               (77),
		.PKT_THREAD_ID_H           (73),
		.PKT_THREAD_ID_L           (73),
		.PKT_BURST_SIZE_H          (64),
		.PKT_BURST_SIZE_L          (62),
		.PKT_TRANS_EXCLUSIVE       (55),
		.PKT_TRANS_LOCK            (54),
		.PKT_BEGIN_BURST           (69),
		.PKT_PROTECTION_H          (76),
		.PKT_PROTECTION_L          (74),
		.PKT_BURSTWRAP_H           (61),
		.PKT_BURSTWRAP_L           (61),
		.PKT_BYTE_CNT_H            (60),
		.PKT_BYTE_CNT_L            (56),
		.PKT_ADDR_H                (49),
		.PKT_ADDR_L                (18),
		.PKT_TRANS_COMPRESSED_READ (50),
		.PKT_TRANS_POSTED          (51),
		.PKT_TRANS_WRITE           (52),
		.PKT_TRANS_READ            (53),
		.PKT_DATA_H                (15),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (17),
		.PKT_BYTEEN_L              (16),
		.PKT_SRC_ID_H              (71),
		.PKT_SRC_ID_L              (71),
		.PKT_DEST_ID_H             (72),
		.PKT_DEST_ID_L             (72),
		.ST_DATA_W                 (86),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (4),
		.SUPPRESS_0_BYTEEN_RSP     (1),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) read_master_avalon_master_agent (
		.clk                   (clk_50M_clk_clk),                                                              //       clk.clk
		.reset                 (read_master_clock_reset_reset_reset_bridge_in_reset_reset),                    // clk_reset.reset
		.av_address            (read_master_avalon_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (read_master_avalon_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (read_master_avalon_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (read_master_avalon_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (read_master_avalon_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (read_master_avalon_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (read_master_avalon_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (read_master_avalon_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (read_master_avalon_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (read_master_avalon_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (read_master_avalon_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (read_master_avalon_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (read_master_avalon_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (read_master_avalon_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (read_master_avalon_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (read_master_avalon_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                            //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                             //          .data
		.rp_channel            (rsp_mux_src_channel),                                                          //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                    //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                      //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                            //          .ready
		.av_response           (),                                                                             // (terminated)
		.av_writeresponsevalid ()                                                                              // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (103),
		.PKT_ORI_BURST_SIZE_L      (101),
		.PKT_RESPONSE_STATUS_H     (100),
		.PKT_RESPONSE_STATUS_L     (99),
		.PKT_BURST_SIZE_H          (82),
		.PKT_BURST_SIZE_L          (80),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (87),
		.PKT_PROTECTION_H          (94),
		.PKT_PROTECTION_L          (92),
		.PKT_BURSTWRAP_H           (79),
		.PKT_BURSTWRAP_L           (79),
		.PKT_BYTE_CNT_H            (78),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (89),
		.PKT_SRC_ID_L              (89),
		.PKT_DEST_ID_H             (90),
		.PKT_DEST_ID_L             (90),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (104),
		.AVS_BURSTCOUNT_W          (5),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) ddr3_interface_avl_1_agent (
		.clk                     (clk_50M_clk_clk),                                           //             clk.clk
		.reset                   (read_master_clock_reset_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (ddr3_interface_avl_1_agent_m0_address),                     //              m0.address
		.m0_burstcount           (ddr3_interface_avl_1_agent_m0_burstcount),                  //                .burstcount
		.m0_byteenable           (ddr3_interface_avl_1_agent_m0_byteenable),                  //                .byteenable
		.m0_debugaccess          (ddr3_interface_avl_1_agent_m0_debugaccess),                 //                .debugaccess
		.m0_lock                 (ddr3_interface_avl_1_agent_m0_lock),                        //                .lock
		.m0_readdata             (ddr3_interface_avl_1_agent_m0_readdata),                    //                .readdata
		.m0_readdatavalid        (ddr3_interface_avl_1_agent_m0_readdatavalid),               //                .readdatavalid
		.m0_read                 (ddr3_interface_avl_1_agent_m0_read),                        //                .read
		.m0_waitrequest          (ddr3_interface_avl_1_agent_m0_waitrequest),                 //                .waitrequest
		.m0_writedata            (ddr3_interface_avl_1_agent_m0_writedata),                   //                .writedata
		.m0_write                (ddr3_interface_avl_1_agent_m0_write),                       //                .write
		.rp_endofpacket          (ddr3_interface_avl_1_agent_rp_endofpacket),                 //              rp.endofpacket
		.rp_ready                (ddr3_interface_avl_1_agent_rp_ready),                       //                .ready
		.rp_valid                (ddr3_interface_avl_1_agent_rp_valid),                       //                .valid
		.rp_data                 (ddr3_interface_avl_1_agent_rp_data),                        //                .data
		.rp_startofpacket        (ddr3_interface_avl_1_agent_rp_startofpacket),               //                .startofpacket
		.cp_ready                (ddr3_interface_avl_1_cmd_width_adapter_src_ready),          //              cp.ready
		.cp_valid                (ddr3_interface_avl_1_cmd_width_adapter_src_valid),          //                .valid
		.cp_data                 (ddr3_interface_avl_1_cmd_width_adapter_src_data),           //                .data
		.cp_startofpacket        (ddr3_interface_avl_1_cmd_width_adapter_src_startofpacket),  //                .startofpacket
		.cp_endofpacket          (ddr3_interface_avl_1_cmd_width_adapter_src_endofpacket),    //                .endofpacket
		.cp_channel              (ddr3_interface_avl_1_cmd_width_adapter_src_channel),        //                .channel
		.rf_sink_ready           (ddr3_interface_avl_1_agent_rsp_fifo_out_ready),             //         rf_sink.ready
		.rf_sink_valid           (ddr3_interface_avl_1_agent_rsp_fifo_out_valid),             //                .valid
		.rf_sink_startofpacket   (ddr3_interface_avl_1_agent_rsp_fifo_out_startofpacket),     //                .startofpacket
		.rf_sink_endofpacket     (ddr3_interface_avl_1_agent_rsp_fifo_out_endofpacket),       //                .endofpacket
		.rf_sink_data            (ddr3_interface_avl_1_agent_rsp_fifo_out_data),              //                .data
		.rf_source_ready         (ddr3_interface_avl_1_agent_rf_source_ready),                //       rf_source.ready
		.rf_source_valid         (ddr3_interface_avl_1_agent_rf_source_valid),                //                .valid
		.rf_source_startofpacket (ddr3_interface_avl_1_agent_rf_source_startofpacket),        //                .startofpacket
		.rf_source_endofpacket   (ddr3_interface_avl_1_agent_rf_source_endofpacket),          //                .endofpacket
		.rf_source_data          (ddr3_interface_avl_1_agent_rf_source_data),                 //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                             // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                             //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                              //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                             //                .error
		.rdata_fifo_src_ready    (ddr3_interface_avl_1_agent_rdata_fifo_src_ready),           //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (ddr3_interface_avl_1_agent_rdata_fifo_src_valid),           //                .valid
		.rdata_fifo_src_data     (ddr3_interface_avl_1_agent_rdata_fifo_src_data),            //                .data
		.m0_response             (2'b00),                                                     //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                       //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (105),
		.FIFO_DEPTH          (49),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) ddr3_interface_avl_1_agent_rsp_fifo (
		.clk               (clk_50M_clk_clk),                                           //       clk.clk
		.reset             (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (ddr3_interface_avl_1_agent_rf_source_data),                 //        in.data
		.in_valid          (ddr3_interface_avl_1_agent_rf_source_valid),                //          .valid
		.in_ready          (ddr3_interface_avl_1_agent_rf_source_ready),                //          .ready
		.in_startofpacket  (ddr3_interface_avl_1_agent_rf_source_startofpacket),        //          .startofpacket
		.in_endofpacket    (ddr3_interface_avl_1_agent_rf_source_endofpacket),          //          .endofpacket
		.out_data          (ddr3_interface_avl_1_agent_rsp_fifo_out_data),              //       out.data
		.out_valid         (ddr3_interface_avl_1_agent_rsp_fifo_out_valid),             //          .valid
		.out_ready         (ddr3_interface_avl_1_agent_rsp_fifo_out_ready),             //          .ready
		.out_startofpacket (ddr3_interface_avl_1_agent_rsp_fifo_out_startofpacket),     //          .startofpacket
		.out_endofpacket   (ddr3_interface_avl_1_agent_rsp_fifo_out_endofpacket),       //          .endofpacket
		.csr_address       (2'b00),                                                     // (terminated)
		.csr_read          (1'b0),                                                      // (terminated)
		.csr_write         (1'b0),                                                      // (terminated)
		.csr_readdata      (),                                                          // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                      // (terminated)
		.almost_full_data  (),                                                          // (terminated)
		.almost_empty_data (),                                                          // (terminated)
		.in_empty          (1'b0),                                                      // (terminated)
		.out_empty         (),                                                          // (terminated)
		.in_error          (1'b0),                                                      // (terminated)
		.out_error         (),                                                          // (terminated)
		.in_channel        (1'b0),                                                      // (terminated)
		.out_channel       ()                                                           // (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (34),
		.FIFO_DEPTH          (256),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (0),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (3),
		.USE_MEMORY_BLOCKS   (1),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) ddr3_interface_avl_1_agent_rdata_fifo (
		.clk               (clk_50M_clk_clk),                                           //       clk.clk
		.reset             (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (ddr3_interface_avl_1_agent_rdata_fifo_src_data),            //        in.data
		.in_valid          (ddr3_interface_avl_1_agent_rdata_fifo_src_valid),           //          .valid
		.in_ready          (ddr3_interface_avl_1_agent_rdata_fifo_src_ready),           //          .ready
		.out_data          (ddr3_interface_avl_1_agent_rdata_fifo_out_data),            //       out.data
		.out_valid         (ddr3_interface_avl_1_agent_rdata_fifo_out_valid),           //          .valid
		.out_ready         (ddr3_interface_avl_1_agent_rdata_fifo_out_ready),           //          .ready
		.csr_address       (2'b00),                                                     // (terminated)
		.csr_read          (1'b0),                                                      // (terminated)
		.csr_write         (1'b0),                                                      // (terminated)
		.csr_readdata      (),                                                          // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                      // (terminated)
		.almost_full_data  (),                                                          // (terminated)
		.almost_empty_data (),                                                          // (terminated)
		.in_startofpacket  (1'b0),                                                      // (terminated)
		.in_endofpacket    (1'b0),                                                      // (terminated)
		.out_startofpacket (),                                                          // (terminated)
		.out_endofpacket   (),                                                          // (terminated)
		.in_empty          (1'b0),                                                      // (terminated)
		.out_empty         (),                                                          // (terminated)
		.in_error          (1'b0),                                                      // (terminated)
		.out_error         (),                                                          // (terminated)
		.in_channel        (1'b0),                                                      // (terminated)
		.out_channel       ()                                                           // (terminated)
	);

	top_LPC_FPGA_mm_interconnect_0_router router (
		.sink_ready         (read_master_avalon_master_agent_cp_ready),                  //      sink.ready
		.sink_valid         (read_master_avalon_master_agent_cp_valid),                  //          .valid
		.sink_data          (read_master_avalon_master_agent_cp_data),                   //          .data
		.sink_startofpacket (read_master_avalon_master_agent_cp_startofpacket),          //          .startofpacket
		.sink_endofpacket   (read_master_avalon_master_agent_cp_endofpacket),            //          .endofpacket
		.clk                (clk_50M_clk_clk),                                           //       clk.clk
		.reset              (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                          //       src.ready
		.src_valid          (router_src_valid),                                          //          .valid
		.src_data           (router_src_data),                                           //          .data
		.src_channel        (router_src_channel),                                        //          .channel
		.src_startofpacket  (router_src_startofpacket),                                  //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                     //          .endofpacket
	);

	top_LPC_FPGA_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (ddr3_interface_avl_1_agent_rp_ready),                       //      sink.ready
		.sink_valid         (ddr3_interface_avl_1_agent_rp_valid),                       //          .valid
		.sink_data          (ddr3_interface_avl_1_agent_rp_data),                        //          .data
		.sink_startofpacket (ddr3_interface_avl_1_agent_rp_startofpacket),               //          .startofpacket
		.sink_endofpacket   (ddr3_interface_avl_1_agent_rp_endofpacket),                 //          .endofpacket
		.clk                (clk_50M_clk_clk),                                           //       clk.clk
		.reset              (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                                      //       src.ready
		.src_valid          (router_001_src_valid),                                      //          .valid
		.src_data           (router_001_src_data),                                       //          .data
		.src_channel        (router_001_src_channel),                                    //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                              //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                 //          .endofpacket
	);

	top_LPC_FPGA_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (clk_50M_clk_clk),                                           //       clk.clk
		.reset              (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                                          //      sink.ready
		.sink_channel       (router_src_channel),                                        //          .channel
		.sink_data          (router_src_data),                                           //          .data
		.sink_startofpacket (router_src_startofpacket),                                  //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                    //          .endofpacket
		.sink_valid         (router_src_valid),                                          //          .valid
		.src0_ready         (cmd_demux_src0_ready),                                      //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                      //          .valid
		.src0_data          (cmd_demux_src0_data),                                       //          .data
		.src0_channel       (cmd_demux_src0_channel),                                    //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                              //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                 //          .endofpacket
	);

	top_LPC_FPGA_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (clk_50M_clk_clk),                                           //       clk.clk
		.reset               (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                         //       src.ready
		.src_valid           (cmd_mux_src_valid),                                         //          .valid
		.src_data            (cmd_mux_src_data),                                          //          .data
		.src_channel         (cmd_mux_src_channel),                                       //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                 //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                   //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                      //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                      //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                    //          .channel
		.sink0_data          (cmd_demux_src0_data),                                       //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                              //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                                 //          .endofpacket
	);

	top_LPC_FPGA_mm_interconnect_0_cmd_demux rsp_demux (
		.clk                (clk_50M_clk_clk),                                           //       clk.clk
		.reset              (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (ddr3_interface_avl_1_rsp_width_adapter_src_ready),          //      sink.ready
		.sink_channel       (ddr3_interface_avl_1_rsp_width_adapter_src_channel),        //          .channel
		.sink_data          (ddr3_interface_avl_1_rsp_width_adapter_src_data),           //          .data
		.sink_startofpacket (ddr3_interface_avl_1_rsp_width_adapter_src_startofpacket),  //          .startofpacket
		.sink_endofpacket   (ddr3_interface_avl_1_rsp_width_adapter_src_endofpacket),    //          .endofpacket
		.sink_valid         (ddr3_interface_avl_1_rsp_width_adapter_src_valid),          //          .valid
		.src0_ready         (rsp_demux_src0_ready),                                      //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                      //          .valid
		.src0_data          (rsp_demux_src0_data),                                       //          .data
		.src0_channel       (rsp_demux_src0_channel),                                    //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                              //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                 //          .endofpacket
	);

	top_LPC_FPGA_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (clk_50M_clk_clk),                                           //       clk.clk
		.reset               (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                         //       src.ready
		.src_valid           (rsp_mux_src_valid),                                         //          .valid
		.src_data            (rsp_mux_src_data),                                          //          .data
		.src_channel         (rsp_mux_src_channel),                                       //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                 //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                   //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                      //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                      //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                    //          .channel
		.sink0_data          (rsp_demux_src0_data),                                       //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                              //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                 //          .endofpacket
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (49),
		.IN_PKT_ADDR_L                 (18),
		.IN_PKT_DATA_H                 (15),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (17),
		.IN_PKT_BYTEEN_L               (16),
		.IN_PKT_BYTE_CNT_H             (60),
		.IN_PKT_BYTE_CNT_L             (56),
		.IN_PKT_TRANS_COMPRESSED_READ  (50),
		.IN_PKT_TRANS_WRITE            (52),
		.IN_PKT_BURSTWRAP_H            (61),
		.IN_PKT_BURSTWRAP_L            (61),
		.IN_PKT_BURST_SIZE_H           (64),
		.IN_PKT_BURST_SIZE_L           (62),
		.IN_PKT_RESPONSE_STATUS_H      (82),
		.IN_PKT_RESPONSE_STATUS_L      (81),
		.IN_PKT_TRANS_EXCLUSIVE        (55),
		.IN_PKT_BURST_TYPE_H           (66),
		.IN_PKT_BURST_TYPE_L           (65),
		.IN_PKT_ORI_BURST_SIZE_L       (83),
		.IN_PKT_ORI_BURST_SIZE_H       (85),
		.IN_ST_DATA_W                  (86),
		.OUT_PKT_ADDR_H                (67),
		.OUT_PKT_ADDR_L                (36),
		.OUT_PKT_DATA_H                (31),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (35),
		.OUT_PKT_BYTEEN_L              (32),
		.OUT_PKT_BYTE_CNT_H            (78),
		.OUT_PKT_BYTE_CNT_L            (74),
		.OUT_PKT_TRANS_COMPRESSED_READ (68),
		.OUT_PKT_BURST_SIZE_H          (82),
		.OUT_PKT_BURST_SIZE_L          (80),
		.OUT_PKT_RESPONSE_STATUS_H     (100),
		.OUT_PKT_RESPONSE_STATUS_L     (99),
		.OUT_PKT_TRANS_EXCLUSIVE       (73),
		.OUT_PKT_BURST_TYPE_H          (84),
		.OUT_PKT_BURST_TYPE_L          (83),
		.OUT_PKT_ORI_BURST_SIZE_L      (101),
		.OUT_PKT_ORI_BURST_SIZE_H      (103),
		.OUT_ST_DATA_W                 (104),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (0),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) ddr3_interface_avl_1_cmd_width_adapter (
		.clk                  (clk_50M_clk_clk),                                           //       clk.clk
		.reset                (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (cmd_mux_src_valid),                                         //      sink.valid
		.in_channel           (cmd_mux_src_channel),                                       //          .channel
		.in_startofpacket     (cmd_mux_src_startofpacket),                                 //          .startofpacket
		.in_endofpacket       (cmd_mux_src_endofpacket),                                   //          .endofpacket
		.in_ready             (cmd_mux_src_ready),                                         //          .ready
		.in_data              (cmd_mux_src_data),                                          //          .data
		.out_endofpacket      (ddr3_interface_avl_1_cmd_width_adapter_src_endofpacket),    //       src.endofpacket
		.out_data             (ddr3_interface_avl_1_cmd_width_adapter_src_data),           //          .data
		.out_channel          (ddr3_interface_avl_1_cmd_width_adapter_src_channel),        //          .channel
		.out_valid            (ddr3_interface_avl_1_cmd_width_adapter_src_valid),          //          .valid
		.out_ready            (ddr3_interface_avl_1_cmd_width_adapter_src_ready),          //          .ready
		.out_startofpacket    (ddr3_interface_avl_1_cmd_width_adapter_src_startofpacket),  //          .startofpacket
		.in_command_size_data (3'b000)                                                     // (terminated)
	);

	altera_merlin_width_adapter #(
		.IN_PKT_ADDR_H                 (67),
		.IN_PKT_ADDR_L                 (36),
		.IN_PKT_DATA_H                 (31),
		.IN_PKT_DATA_L                 (0),
		.IN_PKT_BYTEEN_H               (35),
		.IN_PKT_BYTEEN_L               (32),
		.IN_PKT_BYTE_CNT_H             (78),
		.IN_PKT_BYTE_CNT_L             (74),
		.IN_PKT_TRANS_COMPRESSED_READ  (68),
		.IN_PKT_TRANS_WRITE            (70),
		.IN_PKT_BURSTWRAP_H            (79),
		.IN_PKT_BURSTWRAP_L            (79),
		.IN_PKT_BURST_SIZE_H           (82),
		.IN_PKT_BURST_SIZE_L           (80),
		.IN_PKT_RESPONSE_STATUS_H      (100),
		.IN_PKT_RESPONSE_STATUS_L      (99),
		.IN_PKT_TRANS_EXCLUSIVE        (73),
		.IN_PKT_BURST_TYPE_H           (84),
		.IN_PKT_BURST_TYPE_L           (83),
		.IN_PKT_ORI_BURST_SIZE_L       (101),
		.IN_PKT_ORI_BURST_SIZE_H       (103),
		.IN_ST_DATA_W                  (104),
		.OUT_PKT_ADDR_H                (49),
		.OUT_PKT_ADDR_L                (18),
		.OUT_PKT_DATA_H                (15),
		.OUT_PKT_DATA_L                (0),
		.OUT_PKT_BYTEEN_H              (17),
		.OUT_PKT_BYTEEN_L              (16),
		.OUT_PKT_BYTE_CNT_H            (60),
		.OUT_PKT_BYTE_CNT_L            (56),
		.OUT_PKT_TRANS_COMPRESSED_READ (50),
		.OUT_PKT_BURST_SIZE_H          (64),
		.OUT_PKT_BURST_SIZE_L          (62),
		.OUT_PKT_RESPONSE_STATUS_H     (82),
		.OUT_PKT_RESPONSE_STATUS_L     (81),
		.OUT_PKT_TRANS_EXCLUSIVE       (55),
		.OUT_PKT_BURST_TYPE_H          (66),
		.OUT_PKT_BURST_TYPE_L          (65),
		.OUT_PKT_ORI_BURST_SIZE_L      (83),
		.OUT_PKT_ORI_BURST_SIZE_H      (85),
		.OUT_ST_DATA_W                 (86),
		.ST_CHANNEL_W                  (1),
		.OPTIMIZE_FOR_RSP              (0),
		.RESPONSE_PATH                 (1),
		.CONSTANT_BURST_SIZE           (1),
		.PACKING                       (1),
		.ENABLE_ADDRESS_ALIGNMENT      (0)
	) ddr3_interface_avl_1_rsp_width_adapter (
		.clk                  (clk_50M_clk_clk),                                           //       clk.clk
		.reset                (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_valid             (router_001_src_valid),                                      //      sink.valid
		.in_channel           (router_001_src_channel),                                    //          .channel
		.in_startofpacket     (router_001_src_startofpacket),                              //          .startofpacket
		.in_endofpacket       (router_001_src_endofpacket),                                //          .endofpacket
		.in_ready             (router_001_src_ready),                                      //          .ready
		.in_data              (router_001_src_data),                                       //          .data
		.out_endofpacket      (ddr3_interface_avl_1_rsp_width_adapter_src_endofpacket),    //       src.endofpacket
		.out_data             (ddr3_interface_avl_1_rsp_width_adapter_src_data),           //          .data
		.out_channel          (ddr3_interface_avl_1_rsp_width_adapter_src_channel),        //          .channel
		.out_valid            (ddr3_interface_avl_1_rsp_width_adapter_src_valid),          //          .valid
		.out_ready            (ddr3_interface_avl_1_rsp_width_adapter_src_ready),          //          .ready
		.out_startofpacket    (ddr3_interface_avl_1_rsp_width_adapter_src_startofpacket),  //          .startofpacket
		.in_command_size_data (3'b000)                                                     // (terminated)
	);

	top_LPC_FPGA_mm_interconnect_0_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_50M_clk_clk),                                           // in_clk_0.clk
		.in_rst_0_reset (read_master_clock_reset_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (ddr3_interface_avl_1_agent_rdata_fifo_out_data),            //     in_0.data
		.in_0_valid     (ddr3_interface_avl_1_agent_rdata_fifo_out_valid),           //         .valid
		.in_0_ready     (ddr3_interface_avl_1_agent_rdata_fifo_out_ready),           //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                              //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                             //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                             //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                              //         .error
	);

endmodule
